{"uuid":"564e9c09-d81e-461b-9254-a94f42963c5e","historyId":"5b4b772f279b49014012221765120f21","fullName":"login_demo.DBSearch.test","labels":[{"name":"package","value":"login_demo.DBSearch"},{"name":"testClass","value":"login_demo.DBSearch"},{"name":"testMethod","value":"test"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"webTest"},{"name":"subSuite","value":"login_demo.DBSearch"},{"name":"host","value":"DESKTOP-KGEM189"},{"name":"thread","value":"15624@DESKTOP-KGEM189.main(1)"}],"links":[],"name":"test","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.","trace":"com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:590)\r\n\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:57)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)\r\n\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:664)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:247)\r\n\tat login_demo.DBSearch.test(DBSearch.java:149)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:643)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:782)\r\n\tat org.testng.TestRunner.run(TestRunner.java:632)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:366)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:268)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\r\n\tat org.testng.TestNG.run(TestNG.java:1064)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)\r\nCaused by: com.mysql.cj.core.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\r\n\tat com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)\r\n\tat com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:93)\r\n\tat com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:133)\r\n\tat com.mysql.cj.core.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:149)\r\n\tat com.mysql.cj.mysqla.io.MysqlaProtocol.negotiateSSLConnection(MysqlaProtocol.java:309)\r\n\tat com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.negotiateSSLConnection(MysqlaAuthenticationProvider.java:769)\r\n\tat com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(MysqlaAuthenticationProvider.java:482)\r\n\tat com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.connect(MysqlaAuthenticationProvider.java:204)\r\n\tat com.mysql.cj.mysqla.io.MysqlaProtocol.connect(MysqlaProtocol.java:1414)\r\n\tat com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:132)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1726)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)\r\n\t... 29 more\r\nCaused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\r\n\tat sun.security.ssl.Alerts.getSSLException(Alerts.java:192)\r\n\tat sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)\r\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)\r\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)\r\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1640)\r\n\tat sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)\r\n\tat sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)\r\n\tat sun.security.ssl.Handshaker.process_record(Handshaker.java:965)\r\n\tat sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)\r\n\tat sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)\r\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)\r\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)\r\n\tat com.mysql.cj.core.io.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:156)\r\n\tat com.mysql.cj.mysqla.io.MysqlaProtocol.negotiateSSLConnection(MysqlaProtocol.java:304)\r\n\t... 36 more\r\nCaused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\r\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)\r\n\tat sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)\r\n\tat sun.security.validator.Validator.validate(Validator.java:262)\r\n\tat sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)\r\n\tat sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)\r\n\tat sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)\r\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1622)\r\n\t... 45 more\r\nCaused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\r\n\tat sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)\r\n\tat sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)\r\n\tat java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)\r\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)\r\n\t... 51 more\r\n"},"stage":"finished","start":1594995383970,"stop":1594995385589,"parameters":[]}